import type { Doc, Template } from '../data/types';
import { assemble, type Assembled } from './assemble';
import { dataUrlBytes, verifySeal } from './signature';

type Tpl = Pick<Template, 'id' | 'fields' | 'sections' | 'regimeShort' | 'regime' | 'name'>;

export interface ExportInput { template: Tpl; doc: Pick<Doc, 'values' | 'name' | 'status' | 'by'> & Partial<Pick<Doc, 'signature'>>; company: string }

function subtitle(t: Tpl): string { return t.regime; }

/** The signature image goes into the document only while the seal still matches the content. */
function sealFor(inp: ExportInput) {
  const sig = inp.doc.signature || null;
  const state = verifySeal(inp.template, { values: inp.doc.values, signature: sig });
  return { sig, state, valid: state === 'valid' };
}
function sealLine(inp: ExportInput): string {
  const { sig, state } = sealFor(inp);
  if (!sig) return 'Not signed';
  return (state === 'valid' ? 'Signed by ' + sig.signer + ' on ' + new Date(sig.signedAt).toUTCString() + ' · SHA-256 ' + sig.hash : 'UNSIGNED COPY — content changed after ' + sig.signer + ' signed; seal ' + sig.hash.slice(0, 12) + '… no longer matches');
}

// ---------------------------------------------------------------------------
// PDF — jsPDF, A4, one flow: title, regime line, sections, tables, signature rules
// ---------------------------------------------------------------------------
export async function buildPdf(inp: ExportInput): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF({ unit: 'pt', format: 'a4' });
  const a = assemble(inp.template, inp.doc.values);
  const W = 595.28, M = 56, maxW = W - M * 2;
  let y = M;
  const ensure = (h: number) => { if (y + h > 841.89 - M) { pdf.addPage(); y = M; } };
  const text = (s: string, size: number, bold = false, color = 30) => {
    pdf.setFont('helvetica', bold ? 'bold' : 'normal'); pdf.setFontSize(size); pdf.setTextColor(color);
    const lines = pdf.splitTextToSize(s, maxW) as string[];
    for (const l of lines) { ensure(size * 1.4); pdf.text(l, M, y); y += size * 1.4; }
  };
  for (const r of a.sections) {
    if (!r.included) continue;
    const s = r.section;
    if (s.title) {
      text(s.heading, 15, true);
      for (const l of r.lines) text(l.value, 9, false, 90);
      y += 4; ensure(2); pdf.setDrawColor(30); pdf.setLineWidth(1.2); pdf.line(M, y, W - M, y); y += 14;
      continue;
    }
    y += 6;
    if (s.heading) text(s.heading.toUpperCase(), 10, true, 70);
    for (const l of r.lines) {
      if (l.kind === 'pair') {
        pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); pdf.setTextColor(90);
        ensure(14);
        pdf.text(l.label + ': ', M, y);
        const w = pdf.getTextWidth(l.label + ': ');
        pdf.setTextColor(20); pdf.setFont('helvetica', 'bold');
        const lines = pdf.splitTextToSize(l.value || '______', maxW - w) as string[];
        pdf.text(lines[0], M + w, y); y += 14;
        for (const extra of lines.slice(1)) { ensure(14); pdf.text(extra, M + w, y); y += 14; }
      } else text(l.value, 10, false, 40);
    }
    if (s.table) {
      const cols = s.table.cols.length; const cw = maxW / cols;
      ensure(16); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(9); pdf.setTextColor(70);
      s.table.cols.forEach((c, i) => pdf.text(c, M + i * cw, y)); y += 6; pdf.setDrawColor(200); pdf.setLineWidth(0.5); pdf.line(M, y, W - M, y); y += 12;
      pdf.setFont('helvetica', 'normal'); pdf.setTextColor(30);
      for (const row of s.table.rows) { ensure(14); row.forEach((c, i) => pdf.text(String(c).slice(0, 40), M + i * cw, y)); y += 14; }
    }
    if (s.signature) {
      const seal = sealFor(inp);
      y += 8; ensure(64);
      if (seal.valid && seal.sig) {
        // 120 × 40 pt box, image kept in proportion
        const dims = pdf.getImageProperties(seal.sig.png);
        const h = Math.min(40, (120 * dims.height) / dims.width), w = (h * dims.width) / dims.height;
        pdf.addImage(seal.sig.png, 'PNG', M + 4, y, w, h);
        y += 44;
      } else y += 18;
      pdf.setDrawColor(30); pdf.setLineWidth(0.8); pdf.line(M, y, M + 200, y); pdf.line(W - M - 160, y, W - M, y);
      y += 12; pdf.setFontSize(8); pdf.setTextColor(110); pdf.setFont('helvetica', 'normal');
      pdf.text('Signature' + (seal.valid && seal.sig ? ' — ' + seal.sig.signer : ''), M, y); pdf.text('Date', W - M - 160, y); y += 10;
    }
  }
  y += 16; ensure(26);
  pdf.setFontSize(8); pdf.setTextColor(140);
  pdf.text('Generated by HelmDocs for ' + inp.company + ' · ' + inp.doc.name + ' · status: ' + inp.doc.status + ' · demo document', M, y);
  y += 11;
  pdf.text(pdf.splitTextToSize(sealLine(inp), maxW) as string[], M, y);
  return pdf.output('blob');
}

// ---------------------------------------------------------------------------
// DOCX — docx package
// ---------------------------------------------------------------------------
export async function buildDocx(inp: ExportInput): Promise<Blob> {
  const d = await import('docx');
  const a = assemble(inp.template, inp.doc.values);
  const children: InstanceType<typeof d.Paragraph | typeof d.Table>[] = [];
  const P = (text: string, o: { bold?: boolean; size?: number; color?: string; spacing?: number; heading?: boolean } = {}) =>
    new d.Paragraph({ spacing: { after: o.spacing ?? 80 }, children: [new d.TextRun({ text, bold: o.bold, size: o.size ?? 20, color: o.color, font: 'Arial' })] });
  for (const r of a.sections) {
    if (!r.included) continue;
    const s = r.section;
    if (s.title) {
      children.push(P(s.heading, { bold: true, size: 30 }));
      for (const l of r.lines) children.push(P(l.value, { size: 18, color: '555555' }));
      children.push(new d.Paragraph({ border: { bottom: { style: d.BorderStyle.SINGLE, size: 12, color: '222222' } }, spacing: { after: 200 }, children: [] }));
      continue;
    }
    if (s.heading) children.push(P(s.heading.toUpperCase(), { bold: true, size: 20, color: '444444', spacing: 60 }));
    for (const l of r.lines) {
      if (l.kind === 'pair') children.push(new d.Paragraph({ spacing: { after: 60 }, children: [new d.TextRun({ text: l.label + ': ', size: 20, color: '555555', font: 'Arial' }), new d.TextRun({ text: l.value || '______', size: 20, bold: true, font: 'Arial' })] }));
      else children.push(P(l.value, { color: '333333' }));
    }
    if (s.table) {
      const cell = (t: string, bold = false) => new d.TableCell({ children: [new d.Paragraph({ children: [new d.TextRun({ text: t, bold, size: 18, font: 'Arial' })] })] });
      children.push(new d.Table({ width: { size: 100, type: d.WidthType.PERCENTAGE }, rows: [new d.TableRow({ children: s.table.cols.map((c) => cell(c, true)) }), ...s.table.rows.map((row) => new d.TableRow({ children: row.map((c) => cell(c)) }))] }));
    }
    if (s.signature) {
      const seal = sealFor(inp);
      if (seal.valid && seal.sig) children.push(new d.Paragraph({ spacing: { before: 200, after: 0 }, children: [new d.ImageRun({ type: 'png', data: dataUrlBytes(seal.sig.png), transformation: { width: 150, height: 50 }, altText: { title: 'Signature', description: 'Signature of ' + seal.sig.signer, name: 'signature' } })] }));
      children.push(new d.Paragraph({ spacing: { before: seal.valid ? 40 : 300, after: 40 }, children: [new d.TextRun({ text: '________________________________        ______________', font: 'Arial' })] }));
      children.push(P('Signature' + (seal.valid && seal.sig ? ' — ' + seal.sig.signer : '') + '                                                          Date', { size: 16, color: '777777' }));
    }
    children.push(P('', { spacing: 120 }));
  }
  children.push(P('Generated by HelmDocs for ' + inp.company + ' · ' + inp.doc.name + ' · status: ' + inp.doc.status + ' · demo document', { size: 16, color: '888888' }));
  children.push(P(sealLine(inp), { size: 14, color: '888888' }));
  const document = new d.Document({ creator: 'HelmDocs', title: inp.doc.name, description: subtitle(inp.template), sections: [{ children }] });
  return d.Packer.toBlob(document);
}

// ---------------------------------------------------------------------------
// HTML — used for the print / HTML export
// ---------------------------------------------------------------------------
export function buildHtml(inp: ExportInput, a: Assembled = assemble(inp.template, inp.doc.values)): string {
  const esc = (s: string) => s.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));
  const body = a.sections.filter((r) => r.included).map((r) => {
    const s = r.section;
    if (s.title) return '<h1>' + esc(s.heading) + '</h1>' + r.lines.map((l) => '<p class="sub">' + esc(l.value) + '</p>').join('') + '<hr>';
    return '<section>' + (s.heading ? '<h2>' + esc(s.heading) + '</h2>' : '') +
      r.lines.map((l) => (l.kind === 'pair' ? '<p><span class="lbl">' + esc(l.label!) + ':</span> <b>' + esc(l.value || '______') + '</b></p>' : '<p>' + esc(l.value) + '</p>')).join('') +
      (s.table ? '<table><tr>' + s.table.cols.map((c) => '<th>' + esc(c) + '</th>').join('') + '</tr>' + s.table.rows.map((row) => '<tr>' + row.map((c) => '<td>' + esc(c) + '</td>').join('') + '</tr>').join('') + '</table>' : '') +
      (s.signature ? (sealFor(inp).valid ? '<img class="sigimg" src="' + inp.doc.signature!.png + '" alt="Signature of ' + esc(inp.doc.signature!.signer) + '">' : '') + '<div class="sig"><span>Signature' + (sealFor(inp).valid ? ' — ' + esc(inp.doc.signature!.signer) : '') + '</span><span>Date</span></div>' : '') + '</section>';
  }).join('');
  return '<!doctype html><html><head><meta charset="utf-8"><title>' + esc(inp.doc.name) + '</title><style>body{font:13px/1.55 Arial,sans-serif;color:#1a1a1a;max-width:720px;margin:40px auto;padding:0 24px}h1{font-size:18px;margin:0}h2{font-size:12px;letter-spacing:.06em;color:#4a4a4a;margin:18px 0 6px}.sub{color:#4a4a4a;font-size:11.5px;margin:2px 0}hr{border:0;border-top:2px solid #1a1a1a;margin:12px 0}p{margin:4px 0}.lbl{color:#5a5a5a}table{border-collapse:collapse;width:100%;margin-top:8px}th,td{text-align:left;padding:4px 6px;border-bottom:1px solid #d9d4c7;font-size:12px}.sig{display:flex;justify-content:space-between;margin-top:30px;border-top:1px solid #1a1a1a;padding-top:4px;font-size:11px;color:#5a5a5a}.sigimg{display:block;height:44px;margin:24px 0 -26px 4px}.foot{margin-top:30px;font-size:10px;color:#888}@media print{body{margin:0}}</style></head><body>' + body +
    '<p class="foot">Generated by HelmDocs for ' + esc(inp.company) + ' · ' + esc(inp.doc.name) + ' · status: ' + inp.doc.status + ' · demo document<br>' + esc(sealLine(inp)) + '</p></body></html>';
}

// ---------------------------------------------------------------------------
// Email — mailto with the summary (no SMTP in an offline POC)
// ---------------------------------------------------------------------------
export function mailtoUrl(inp: ExportInput, to = ''): string {
  const a = assemble(inp.template, inp.doc.values);
  const subject = inp.template.name + ' — ' + inp.doc.name;
  const body = 'Please find the ' + inp.template.name + ' (' + inp.template.regimeShort + ') for review.\n\n' + a.text.slice(0, 1500) + '\n\nSent from HelmDocs by ' + inp.doc.by + ' · ' + inp.company;
  return 'mailto:' + encodeURIComponent(to) + '?subject=' + encodeURIComponent(subject) + '&body=' + encodeURIComponent(body);
}

// ---------------------------------------------------------------------------
// Tabular data extraction — CSV / TSV / XML / XLSX
// ---------------------------------------------------------------------------
export type Row = Record<string, string | number | null>;

function cellCsv(v: string | number | null, sep: string): string {
  const s = v === null || v === undefined ? '' : String(v);
  return /["\n\r]/.test(s) || s.includes(sep) ? '"' + s.replace(/"/g, '""') + '"' : s;
}
export function toCsv(rows: Row[], sep = ','): string {
  if (!rows.length) return '';
  const cols = Object.keys(rows[0]);
  return [cols.join(sep), ...rows.map((r) => cols.map((c) => cellCsv(r[c], sep)).join(sep))].join('\n');
}
export function toTsv(rows: Row[]): string { return toCsv(rows, '\t'); }

const xmlEsc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c] as string));
export function toXml(rows: Row[], root = 'documents', item = 'record'): string {
  const tag = (k: string) => k.replace(/[^A-Za-z0-9_]/g, '_').replace(/^(\d)/, '_$1');
  return '<?xml version="1.0" encoding="UTF-8"?>\n<' + root + '>\n' + rows.map((r) => '  <' + item + '>' + Object.entries(r).map(([k, v]) => '<' + tag(k) + '>' + xmlEsc(v === null || v === undefined ? '' : String(v)) + '</' + tag(k) + '>').join('') + '</' + item + '>').join('\n') + '\n</' + root + '>';
}

/** Minimal OOXML workbook (inline strings) built with jszip — opens in Excel / Numbers / LibreOffice. */
export async function toXlsx(rows: Row[], sheet = 'Documents'): Promise<Blob> {
  const JSZip = (await import('jszip')).default;
  const cols = rows.length ? Object.keys(rows[0]) : [];
  const colRef = (i: number) => { let s = ''; i++; while (i > 0) { const m = (i - 1) % 26; s = String.fromCharCode(65 + m) + s; i = Math.floor((i - 1) / 26); } return s; };
  const cell = (r: number, c: number, v: string | number | null) => {
    if (typeof v === 'number' && Number.isFinite(v)) return '<c r="' + colRef(c) + r + '"><v>' + v + '</v></c>';
    return '<c r="' + colRef(c) + r + '" t="inlineStr"><is><t>' + xmlEsc(v === null || v === undefined ? '' : String(v)) + '</t></is></c>';
  };
  const rowsXml = ['<row r="1">' + cols.map((c, i) => cell(1, i, c)).join('') + '</row>', ...rows.map((r, ri) => '<row r="' + (ri + 2) + '">' + cols.map((c, i) => cell(ri + 2, i, r[c])).join('') + '</row>')].join('');
  const zip = new JSZip();
  zip.file('[Content_Types].xml', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');
  zip.file('_rels/.rels', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
  zip.file('xl/workbook.xml', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="' + xmlEsc(sheet) + '" sheetId="1" r:id="rId1"/></sheets></workbook>');
  zip.file('xl/_rels/workbook.xml.rels', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');
  zip.file('xl/worksheets/sheet1.xml', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>' + rowsXml + '</sheetData></worksheet>');
  return zip.generateAsync({ type: 'blob', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}

export function saveBlob(blob: Blob, name: string) {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = name;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 1000);
}
